module.exports = {
    processor: '@mapbox/stylelint-processor-arbitrary-tags', // Указываем процессор для обработки тегов
    extends: [
        'stylelint-config-standard', // Базовые правила CSS
        'stylelint-config-standard-scss', // SCSS-правила
        'stylelint-config-css-modules',
        'stylelint-config-recommended-vue', // Рекомендуемые правила для Vue
    ],
    plugins: ['stylelint-order'], // Поддержка упорядочивания правил
    rules: {
        // Здесь можно настроить или переопределить правила Stylelint
        'at-rule-no-unknown': null, // Отключаем, чтобы избежать ошибок с Vue специфическими атрибутами
        'no-empty-source': null, // Полезно для работы с пустыми style блоками
        // Упорядочивание свойств
        'order/properties-order': [
            'content',
            'position',
            'top',
            'right',
            'bottom',
            'left',
            'z-index',
            'visibility',
            'box-sizing',
            'overflow',
            'overflow-x',
            'overflow-y',
            'display',
            'align-items',
            'justify-content',
            'align-content',
            'align-self',
            'flex',
            'flex-flow',
            'flex-grow',
            'flex-shrink',
            'flex-wrap',
            'order',
            'float',
            'width',
            'min-width',
            'max-width',
            'height',
            'min-height',
            'max-height',
            'margin',
            'margin-top',
            'margin-right',
            'margin-bottom',
            'margin-left',
            'padding',
            'padding-top',
            'padding-right',
            'padding-bottom',
            'padding-left',
            'border-radius',
            'border',
            'border-color',
            'border-style',
            'border-width',
            'border-top',
            'border-top-color',
            'border-top-style',
            'border-top-width',
            'border-right',
            'border-right-color',
            'border-right-style',
            'border-right-width',
            'border-bottom',
            'border-bottom-color',
            'border-bottom-style',
            'border-bottom-width',
            'border-left',
            'border-left-color',
            'border-left-style',
            'border-left-width',
            'border-spacing',
            'background',
            'background-attachment',
            'background-clip',
            'background-color',
            'background-image',
            'background-origin',
            'background-position',
            'background-repeat',
            'background-size',
            'clip',
            'outline',
            'outline-color',
            'outline-offset',
            'outline-style',
            'outline-width',
            'list-style',
            'list-style-image',
            'list-style-position',
            'list-style-type',
            'columns',
            'column-count',
            'column-fill',
            'column-gap',
            'column-rule',
            'column-rule-color',
            'column-rule-style',
            'column-rule-width',
            'column-span',
            'column-width',
            'vertical-align',
            'text-align',
            'text-align-last',
            'text-decoration',
            'text-decoration-color',
            'text-decoration-line',
            'text-decoration-style',
            'text-indent',
            'text-justify',
            'text-overflow',
            'text-shadow',
            'text-transform',
            'white-space',
            'word-beak',
            'word-spacing',
            'word-wrap',
            'font',
            'font-family',
            'font-size',
            'font-weight',
            'font-style',
            'font-variant',
            'line-height',
            'letter-spacing',
            'color',
            'opacity',
            'transform',
            'transform-origin',
            'transition',
            'transition-delay',
            'transition-duration',
            'transition-property',
            'transition-timing-function',
            'animation',
            'animation-name',
            'animation-duration',
            'animation-delay',
            'animation-fill-mode',
            'animation-direction',
            'animation-iteration-count',
            'animation-play-state',
            'animation-timing-function',
            'cursor',
        ],

        // Отключаем запрет неизвестных псевдоэлементов
        'selector-pseudo-element-no-unknown': [
            true,
            { ignorePseudoElements: ['v-deep'] },
        ],

        // Пример кастомных правил
        'color-no-invalid-hex': true, // Запрет некорректных HEX-кодов
    },
    overrides: [
        {
            files: ['**/*.scss'], // Настройки для SCSS
            customSyntax: 'postcss-scss',
        },
        {
            files: ['**/*.css', '**/*.scss'], // Файлы для обработки
            rules: {
                // Кастомные правила для SCSS
                'no-empty-source': null,
            },
        },
    ],
};
